version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www/html
    volumes:
      - ~/www/swoole_show:/var/www/html
    ports:
      - 80:80
      - 8888:8888
#    command: composer install --no-progress --no-interaction --ansi --ignore-platform-reqs
    networks:
      - mynet

  db:
    image: mysql:5.7.15
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
      - "3306:3306"
    networks:
      - mynet

volumes:
  dbdata:

networks:
  mynet:
